import 'package:bloc_app/core/common/cubit/app_user/app_user_cubit.dart';
import 'package:bloc_app/core/network/connection_checker.dart';
import 'package:bloc_app/core/secrets/app_secrets.dart';
import 'package:bloc_app/features/auth/data/datasource/auth_remote_data_source.dart';
import 'package:bloc_app/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:bloc_app/features/auth/domain/repostiory/auth_repository.dart';
import 'package:bloc_app/features/auth/domain/usecases/current_user.dart';
import 'package:bloc_app/features/auth/domain/usecases/user_login.dart';
import 'package:bloc_app/features/auth/domain/usecases/user_sign_up.dart';
import 'package:bloc_app/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:bloc_app/features/blog/data/datasource/bloc_local_data_source.dart';
import 'package:bloc_app/features/blog/data/datasource/blog_remote_data_source.dart';
import 'package:bloc_app/features/blog/data/repositories/blog_reopsitory_impl.dart';
import 'package:bloc_app/features/blog/domain/repositories/blog_repository.dart';
import 'package:bloc_app/features/blog/domain/usecases/get_all_blog.dart';
import 'package:bloc_app/features/blog/domain/usecases/upload_blog.dart';
import 'package:bloc_app/features/blog/presentation/bloc/blog_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:hive/hive.dart' show Hive;
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'init_dependencies_main.dart';